% Bertrand liechtenstein & Iliar Mangutov & Shanshan Ni & Sean Filipov
% Topics in economics, Final Project
function [all_etfs, indices, etf_data_set] = load_etf(begining_index)
  etf_directory='..\data\asset-and-asset-classes\portfolio-etfs\';
  files = {'etf_bond_agg_ishares_core_us_aggregate_bond_monthly.xls' ...
           'etf_bond_bnd_vanguard_total_bond_market_etf_monthly.xls' ...
           'etf_bond_bsv_vanguard_short_term_bond_monthly.xls' ...
           'etf_bond_mbb_ishares_mbs_monthly.xls' ...
           'etf_bond_tip_ishares_tips_bond_monthly.xls' ...
           'etf_don_wisdomtree_midcap_dividend_monthly.xls' ...
           'etf_eem_ishares_msci_emerging_markets_monthly.xls' ...
           'etf_ewj_ishares_msci_japan_monthly.xls' ...
           'etf_fxi_ishares_china_large_cap_monthly.xls' ...
           'etf_iwm_ishares_russell_2000_monthly.xls' ...
           'etf_pjp_powershares_dynamic_pharmaceuticals_monthly.xls' ...
           'etf_rom_proshares_ultra_technology_monthly.xls' ...
           'etf_rwj_revenueshares_small_cap_monthly.xls' ...
           'etf_rxl_proshares_ultra_health_care_monthly.xls' ...
           'etf_slv_ishares_silver_trust_monthly.xls' ...
           'etf_ucc_proshares_ultra_consumer_services_monthly.xls' ...
           'etf_uge_proshares_ultra_consumer_goods_monthly.xls' ...
           'etf_ung_united_states_natural_gas_monthly.xls' ...
           'etf_upw_proshares_ultra_utilities_monthly.xls' ...
           'etf_ure_proshares_ultra_real_estate_monthly.xls' ...
           'etf_uso_united_states_oil_monthly.xls' ...
           'etf_uxi_proshares_ultra_industrials_monthly.xls' ...
           'etf_uyg_proshares_ultra_financials_monthly.xls' ...
           'etf_uym_proshares_ultra_basic_materials_monthly.xls' ...
           'etf_vbk_vanguard_small_cap_growth_monthly.xls' ...
           'etf_vwo_vanguard_emerging_markets_stock_idx_monthly.xls' ...
           'etf_xle_energy_select_sector_spdr_monthly.xls' ...
           'etf_xlf_financial_select_sector_spdr_monthly.xls' ...
           'etf_xli_industrial_select_sector_spdr_monthly.xls'};
  close_price_index = 4;
           
  for file_index = 1:size(files,2)
    file_name = strcat(etf_directory, files{file_index});
    [level_data,~,raw_data] = xlsread(file_name);
    dates_list = datenum(raw_data(2:end,1));
    data_dates = year(dates_list)*100+month(dates_list);
    etf_data = [data_dates level_data(:,close_price_index)];
    etfs{file_index} = etf_data;
  end
  clear file_index raw_data level_data dates_list data_dates close_price_index files etf_data etf_directory file_name;

  % get intersect with the risk free rate.
  for etf_index = 1:size(etfs,2)
    etf_data = etfs{1,etf_index};
    returns = 12.0 * (etf_data(1:end-1,2)-etf_data(2:end,2))./etf_data(2:end,2);
    etfs{1,etf_index}(1:end-1,2) = returns;
    etfs{1,etf_index}(end,:) = [];
  end
  
  etf_data_set = etfs;
  
  asset = etfs{1,1};
  timestamp_array = asset(:,1);
  for ndx = 2:size(etfs,2)
    asset = etfs{1,ndx};
    timestamp_array = intersect(timestamp_array,asset(:,1));
  end
  
  %TODO - do not assume 29 etfs, run in loop
  all_etfs = horzcat(timestamp_array,...
                    get_intersect_array(timestamp_array,etfs{1,1}),...
                    get_intersect_array(timestamp_array,etfs{1,2}),...
                    get_intersect_array(timestamp_array,etfs{1,3}),...
                    get_intersect_array(timestamp_array,etfs{1,4}),...
                    get_intersect_array(timestamp_array,etfs{1,5}),...
                    get_intersect_array(timestamp_array,etfs{1,6}),...
                    get_intersect_array(timestamp_array,etfs{1,7}),...
                    get_intersect_array(timestamp_array,etfs{1,8}),...
                    get_intersect_array(timestamp_array,etfs{1,9}),...
                    get_intersect_array(timestamp_array,etfs{1,10}),...
                    get_intersect_array(timestamp_array,etfs{1,11}),...
                    get_intersect_array(timestamp_array,etfs{1,12}),...
                    get_intersect_array(timestamp_array,etfs{1,13}),...
                    get_intersect_array(timestamp_array,etfs{1,14}),...
                    get_intersect_array(timestamp_array,etfs{1,15}),...
                    get_intersect_array(timestamp_array,etfs{1,16}),...
                    get_intersect_array(timestamp_array,etfs{1,17}),...
                    get_intersect_array(timestamp_array,etfs{1,18}),...
                    get_intersect_array(timestamp_array,etfs{1,19}),...
                    get_intersect_array(timestamp_array,etfs{1,20}),...
                    get_intersect_array(timestamp_array,etfs{1,21}),...
                    get_intersect_array(timestamp_array,etfs{1,22}),...
                    get_intersect_array(timestamp_array,etfs{1,23}),...
                    get_intersect_array(timestamp_array,etfs{1,24}),...
                    get_intersect_array(timestamp_array,etfs{1,25}),...
                    get_intersect_array(timestamp_array,etfs{1,26}),...
                    get_intersect_array(timestamp_array,etfs{1,27}),...
                    get_intersect_array(timestamp_array,etfs{1,28}),...
                    get_intersect_array(timestamp_array,etfs{1,29}));
  all_etfs = sortrows(all_etfs,-1);

  indices.date = 1;
  indices.etf_bond_agg_ishares_core_us_aggregate_bond_monthly = 2 + begining_index;
  indices.etf_bond_bnd_vanguard_total_bond_market_etf_monthly = 3 + begining_index;
  indices.etf_bond_bsv_vanguard_short_term_bond_monthly = 4 + begining_index;
  indices.etf_bond_mbb_ishares_mbs_monthly = 5 + begining_index;
  indices.etf_bond_tip_ishares_tips_bond_monthly = 6 + begining_index;
  indices.etf_don_wisdomtree_midcap_dividend_monthly = 7 + begining_index;
  indices.etf_eem_ishares_msci_emerging_markets_monthly = 8 + begining_index;
  indices.etf_ewj_ishares_msci_japan_monthly = 9 + begining_index;
  indices.etf_fxi_ishares_china_large_cap_monthly = 10 + begining_index;
  indices.etf_iwm_ishares_russell_2000_monthly = 11 + begining_index;
  indices.etf_pjp_powershares_dynamic_pharmaceuticals_monthly = 12 + begining_index;
  indices.etf_rom_proshares_ultra_technology_monthly = 13 + begining_index;
  indices.etf_rwj_revenueshares_small_cap_monthly = 14 + begining_index;
  indices.etf_rxl_proshares_ultra_health_care_monthly = 15 + begining_index;
  indices.etf_slv_ishares_silver_trust_monthly = 16 + begining_index;
  indices.etf_ucc_proshares_ultra_consumer_services_monthly = 17 + begining_index;
  indices.etf_uge_proshares_ultra_consumer_goods_monthly = 18 + begining_index;
  indices.etf_ung_united_states_natural_gas_monthly = 19 + begining_index;
  indices.etf_upw_proshares_ultra_utilities_monthly = 20 + begining_index;
  indices.etf_ure_proshares_ultra_real_estate_monthly = 21 + begining_index;
  indices.etf_uso_united_states_oil_monthly = 22 + begining_index;
  indices.etf_uxi_proshares_ultra_industrials_monthly = 23 + begining_index;
  indices.etf_uyg_proshares_ultra_financials_monthly = 24 + begining_index;
  indices.etf_uym_proshares_ultra_basic_materials_monthly = 25 + begining_index;
  indices.etf_vbk_vanguard_small_cap_growth_monthly = 26 + begining_index;
  indices.etf_vwo_vanguard_emerging_markets_stock_idx_monthly = 27 + begining_index;
  indices.etf_xle_energy_select_sector_spdr_monthly = 28 + begining_index;
  indices.etf_xlf_financial_select_sector_spdr_monthly = 29 + begining_index;
  indices.etf_xli_industrial_select_sector_spdr_monthly = 30 + begining_index;  

end